name: On-Demand Rollback

on: repository_dispatch

jobs:
  rollback:
    runs-on: ubuntu-latest
    name: Rollback a microservice to a specific version
    steps:
      - run: echo ${{ github.event }}
      - run: |
          microservice=b
          version=c
          rollback $microservice $version
