name: On-Demand Rollback

on: repository_dispatch

jobs:
  rollback:
    runs-on: ubuntu-latest
    name: Rollback a microservice to a specific version
    steps:
      - run: |
          echo "${{ toJson(github.event.client_payload.microservice) }}" \
               "${{ toJson(github.event.client_payload.version) }}"
